#!/usr/bin/env python3

# This file generates 10 pairs of random strings of A,C,G, and T
# separated by a comma(,).

import sys
import random

NUM_LINES = 10 	
KEY_LEN = int(sys.argv[2]) # argv 2: String Length
fileout = str(sys.argv[1]) # argv 1: Filename

def key_gen():
    keylist = [random.choice(['A','C','G','T']) for i in range(KEY_LEN)]
    return ("".join(keylist))

fout = open(fileout, 'wt')
for i in range(0, NUM_LINES):
	x = key_gen()
	y = key_gen()
	print (x,',',y,sep='', file=fout)
fout.close()
