#!/usr/bin/python3

import sys; sys.path.insert(0, './source')
import bruteforce as BruteForce
import enhanced as ednc
import General as general

# get input file name form command line
inputFileName = str(sys.argv[1])

# declare output file name
outputFileName = "output_enhanceddnc.txt"

# convert text file to 2d list of points
pointList = general.convert(inputFileName)

# sort the list
pointList = general.sortList(pointList)
ysorted = general.sortY(pointList)
# run enhanced dnc min dist algo
(shortestDistance, listOfShortestPoints) = ednc.EnhancedDivideConquer(pointList,ysorted)

# output to file
general.writePairs(shortestDistance,listOfShortestPoints,outputFileName)

